# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

closeMatch <- function(x, y, xidx, yidx, ppm, dmz) {
    .Call('_mineMS2_closeMatch', PACKAGE = 'mineMS2', x, y, xidx, yidx, ppm, dmz)
}

decomposeMass <- function(mass, tolerance, b, components) {
    .Call('_mineMS2_decomposeMass', PACKAGE = 'mineMS2', mass, tolerance, b, components)
}

formulaExtension <- function(masses, mzlim, formula, hatoms, hhatom) {
    .Call('_mineMS2_formulaExtension', PACKAGE = 'mineMS2', masses, mzlim, formula, hatoms, hhatom)
}

mineClosedDags <- function(vertices_list, edges_list, processing, num, k, size_min, prec_only) {
    .Call('_mineMS2_mineClosedDags', PACKAGE = 'mineMS2', vertices_list, edges_list, processing, num, k, size_min, prec_only)
}

MST <- function(edges, scores, num_vertices) {
    .Call('_mineMS2_MST', PACKAGE = 'mineMS2', edges, scores, num_vertices)
}

scorePattern <- function(edges, scores, num_vertices) {
    .Call('_mineMS2_scorePattern', PACKAGE = 'mineMS2', edges, scores, num_vertices)
}

select_patterns_from_spectra <- function(pat_list, sid) {
    .Call('_mineMS2_select_patterns_from_spectra', PACKAGE = 'mineMS2', pat_list, sid)
}

patterns_from_spectra <- function(pat_list, num_spectra) {
    .Call('_mineMS2_patterns_from_spectra', PACKAGE = 'mineMS2', pat_list, num_spectra)
}

FindEqualGreaterM <- function(inv, values) {
    .Call('_mineMS2_FindEqualGreaterM', PACKAGE = 'mineMS2', inv, values)
}

findLimDensity <- function(seq, istart, state) {
    .Call('_mineMS2_findLimDensity', PACKAGE = 'mineMS2', seq, istart, state)
}

formulaFromString <- function(formula, names_atoms) {
    .Call('_mineMS2_formulaFromString', PACKAGE = 'mineMS2', formula, names_atoms)
}

disjointBins <- function(points, lower_lim, upper_lim, mean_bin) {
    .Call('_mineMS2_disjointBins', PACKAGE = 'mineMS2', points, lower_lim, upper_lim, mean_bin)
}

checkInter <- function(a_min, a_max, b_min, b_max) {
    .Call('_mineMS2_checkInter', PACKAGE = 'mineMS2', a_min, a_max, b_min, b_max)
}

find_combinations_ranges <- function(bmin, bmax, cmzmax) {
    .Call('_mineMS2_find_combinations_ranges', PACKAGE = 'mineMS2', bmin, bmax, cmzmax)
}

