# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decomposeMass <- function(mass, tolerance, b, components) {
    .Call('_mineMS2_decomposeMass', PACKAGE = 'mineMS2', mass, tolerance, b, components)
}

formulaExtension <- function(masses, mzlim, formula, hatoms, hhatom) {
    .Call('_mineMS2_formulaExtension', PACKAGE = 'mineMS2', masses, mzlim, formula, hatoms, hhatom)
}

FindEqualGreaterM <- function(inv, values) {
    .Call('_mineMS2_FindEqualGreaterM', PACKAGE = 'mineMS2', inv, values)
}

findLimDensity <- function(seq, istart, state) {
    .Call('_mineMS2_findLimDensity', PACKAGE = 'mineMS2', seq, istart, state)
}

formulaFromString <- function(formula, names_atoms) {
    .Call('_mineMS2_formulaFromString', PACKAGE = 'mineMS2', formula, names_atoms)
}

disjointBins <- function(points, lower_lim, upper_lim, mean_bin) {
    .Call('_mineMS2_disjointBins', PACKAGE = 'mineMS2', points, lower_lim, upper_lim, mean_bin)
}

checkInter <- function(a_min, a_max, b_min, b_max) {
    .Call('_mineMS2_checkInter', PACKAGE = 'mineMS2', a_min, a_max, b_min, b_max)
}

